# helm upgrade -n monitoring prom prometheus-community/kube-prometheus-stack --reset-values -f values/kube-prometheus-values.yaml

nameOverride: kp
grafana:
  useStatefulSet: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: grafana.k8s.somemissing.info
  persistence:
    enabled: true
    storageClassName: zfs-generic-iscsi-csi
  initChownData:
    enabled: false
  sidecar:
    datasources:
      url: http://thanos-query.thanos.svc.cluster.local.:9090
      timeout: 300
      jsonData:
        customQueryParameters: max_source_resolution=1h
        cacheLevel:	Medium
        prometheusType: "Thanos"
        prometheusVersion: "0.31.1"
        queryTimeout: "300s"
  additionalDataSources:
  - name: prometheus_vmubtkube-a
    type: prometheus
    url: http://{{ printf "%s-kp-prometheus.monitoring.svc" .Release.Name }}:9090
prometheusOperator:
  verticalPodAutoscaler:
    enabled: true
additionalPrometheusRulesMap:
  blackbox-exporter-alerts:
    groups:
    - name: ./smoke-test.rules
      rules:
      - alert: BlackboxServiceProbeFailing
        expr: max by (instance, target) (probe_success) != 1
        for: 10m
        annotations:
          summary: A service is failing blackbox probing.
    - name: ./certificates.rules
      rules:
      - alert: CertificatesNearExpiry
        expr: |
          ( probe_ssl_last_chain_expiry_timestamp_seconds - time() ) / 60 / 60 / 24 < 30
        for: 5m
        annotations:
          summary: Certificates are nearing expiration.
  deluge:
    groups:
    - name: ./deluge.rules
      rules:
      - alert: TooManyPausedTorrents
        expr: |
          max(deluge_torrents{state="paused"}) / max(deluge_torrents{state="total"}) > 0.25
        for: 10m
        annotations:
          summary: Too many torrents are paused at the same time.
  frigate:
    groups:
    - name: ./frigate.rules
      rules:
      - alert: FrigateNotProcessing
        expr: |
          sum by (instance) (frigate_process_fps) < 1
        for: 5m
        annotations:
          summary: Frigate doesn't appear to be doing any work.

prometheus:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: prometheus.k8s.somemissing.info
  prometheusSpec:
    #image:
    #  sha: "b1af68dd8294e71031a379ad312f2749724e2ad21c236009a1819fdb5573a72f"
    prometheusExternalLabelNameClear: true
    externalLabels:
      cluster: vmubtkube-a
      prometheus: vmubtkube-a
    retention: 7d
    retentionSize: 15GB
    scrapeInterval: 15s
    remoteWrite:
    - url: http://thanos-receive-router.thanos.svc.cluster.local.:19291/api/v1/receive
      # remoteTimeout: 90s
      remoteTimeout: 300s
      # writeRelabelConfigs:
      #   - sourceLabels: ["__name__"]
      #     targetLabel: cluster
      #     replacement: vmubtkube-a
      headers:
        THANOS-TENANT: vmubtkube-a
      metadataConfig:
        send: false
      sendNativeHistograms: true
      queueConfig:
        batchSendDeadline: 30s
        # maxSamplesPerSend: 5000
        maxSamplesPerSend: 2500
        minBackoff: 25ms
        maxBackoff: 500ms
        retryOnRateLimit: true
        sampleAgeLimit: 5m
      writeRelabelConfigs:
        - sourceLabels: [pod, server, job]
          targetLabel: job
          # Require ; and at least 1 other character (both pod and server can't be empty)
          regex: '.{2,};minio|scrapeConfig/minio-tenant/minio.*'
          replacement: minio-default-minio-job
    resources:
      limits:
        memory: 4Gi
        cpu: 2000m
      requests:
        memory: 3Gi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
          storageClassName: zfs-generic-iscsi-csi
    scrapeConfigSelector:
      matchLabels:
        release: prom
    additionalScrapeConfigs:
    - job_name: 'deluge'
      static_configs:
      - targets: ['vmcent74deluge.homelab.somemissing.info:9354']
    - job_name: jellyfin
      static_configs:
      - targets: ['jellyfin.apps.somemissing.info:80']
    - job_name: 'opnsense'
      scrape_interval: 10s
      static_configs:
      - targets:
        - 'opnsense.homelab.somemissing.info:9100'
        - 'opnsense.homelab.somemissing.info:9273'
    - job_name: node-exporter
      static_configs:
      - targets: ['vmubttorrent01.homelab.somemissing.info:9100']
    - job_name: minio-hdd
      metrics_path: /minio/metrics/v3
      static_configs:
      - targets:
          - nas.apps.somemissing.info.:9000
    - job_name: minio-midline
      metrics_path: /minio/metrics/v3
      static_configs:
      - targets:
          - nas.apps.somemissing.info.:9001
    - job_name: homeassistant
      metrics_path: /api/prometheus
      static_configs:
      - targets:
        - 172.16.2.1:8123
    - job_name: frigate
      metrics_path: /api/metrics
      scheme: https
      static_configs:
      - targets: ['frigate.apps.somemissing.info']