apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metacontroller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  source:
    repoURL: ghcr.io/metacontroller
    chart: metacontroller-helm
    targetRevision: 4.11.18
    helm:
      releaseName: metacontroller
      valuesObject: {}