apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20
    helm:
      releaseName: external-secrets
      valuesObject:
        # helm upgrade --force external-secrets external-secrets/external-secrets -n external-secrets --reset-values -f values/external-secrets-values.yaml
        bitwarden-sdk-server:
          enabled: true

        # I don't think this works
        extraVolumes:
        - name: bitwarden-sdk-ca
          secret:
            secretName: external-secrets-ca
            items:
            - key: ca.crt
              path: bitwarden-sdk-ca.pem
        extraVolumeMounts:
        - name: bitwarden-sdk-ca
          mountPath: /etc/ssl/certs/bitwarden-sdk-ca.pem
          subPath: bitwarden-sdk-ca.pem

        serviceMonitor:
          enabled: true
          interval: 10s
          scrapeTimeout: 8s
          additionalLabels:
            release: prom

        webhook:
          certManager:
            enabled: true
            cert:
              issuerRef:
                name: external-secrets
                kind: Issuer
                group: cert-manager.io

        extraObjects:
        - apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: external-secrets-ca
            namespace: external-secrets
          spec:
            selfSigned: {}

        - apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: external-secrets-ca
            namespace: external-secrets
          spec:
            isCA: true
            commonName: external-secrets-ca
            secretName: external-secrets-ca
            duration: 87660h
            privateKey:
              algorithm: ECDSA
              size: 256
            issuerRef:
              name: external-secrets-ca
              kind: Issuer
              group: cert-manager.io

        - apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: external-secrets
            namespace: external-secrets
          spec:
            ca:
              secretName: external-secrets-ca

        - apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: bitwarden-webhook
            namespace: external-secrets
          spec:
            secretName: bitwarden-tls-certs
            issuerRef:
              name: external-secrets
              kind: Issuer
              group: cert-manager.io
            dnsNames:
              - bitwarden-sdk-server
              - bitwarden-sdk-server.external-secrets
              - bitwarden-sdk-server.external-secrets.svc.cluster.local.

        - apiVersion: external-secrets.io/v1beta1
          kind: ClusterSecretStore
          metadata:
            name: default
            namespace: external-secrets
          spec:
            provider:
              bitwardensecretsmanager:
                # TODO PR in docs
                apiURL: https://api.bitwarden.com
                identityURL: https://identity.bitwarden.com
                auth:
                  secretRef:
                    credentials:
                      key: token
                      name: bitwarden-access-token
                      namespace: external-secrets
                bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local.:9998
                # Copied from bitwarden-tls-secret ca.crt
                # See https://github.com/external-secrets/external-secrets/issues/3676
                caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNLZ0F3SUJBZ0lRWkdzb2Z3OHJnTzdSRzgvcHlLTnFYREFLQmdncWhrak9QUVFEQWpBZU1Sd3cKR2dZRFZRUURFeE5sZUhSbGNtNWhiQzF6WldOeVpYUnpMV05oTUI0WERUSTBNRGN3T1RBeE1UVXlOVm9YRFRJMApNVEF3TnpBeE1UVXlOVm93SGpFY01Cb0dBMVVFQXhNVFpYaDBaWEp1WVd3dGMyVmpjbVYwY3kxallUQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTGdoRENFaGkzMVpBa2VrQkwwT2ZNcjdjUFF3R0ZHeHp1N0EKTlRqRjhucVlDZ3dqZWdPU0hzK0tmQVIrR1IreW9qNU5jdzVTREJlcFQrZ3puNS8zaXplalFqQkFNQTRHQTFVZApEd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlIwMUF2aG1mdEJHS0VaCldvOFJBa05sdDJUaDB6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFtL0JneXBLWE94UTVuSVFaL2xBMUtjS3QKWktlczN6MFhkL3lNT0ExTVVvc0NJUUNneHR2cXlIcng3VncyWkh1ZGhuOGgxRXIyVTVDdzZ3UFpPWS9zcnlpSwpmZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                # caProvider:
                #   type: Secret
                #   namespace: external-secrets
                #   name: external-secrets-ca
                #   key: ca.crt
                organizationID: 0e4bec68-6d2a-40f6-b04e-b1a8000ad930
                projectID: b6655361-e5c6-41ac-ac2f-b1a8000b953d