apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-index-memcached
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: thanos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
  source:
    chart: memcached
    repoURL: registry-1.docker.io/cloudpirates
    targetRevision: 0.14.7
    helm:
      releaseName: index-cache
      valuesObject:
        service:
          type: ClusterIP
          clusterIP: None
        config:
          memoryLimit: 256
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 1250m
            memory: 600Mi
        pdb:
          create: true
          minAvailable: "0" # not HA
        metrics:
          enabled: true
          image:
            registry: docker.io
            repository: prom/memcached-exporter
            tag: "v0.17.0"
          serviceMonitor:
            enabled: true
            interval: 10s
            labels:
              release: prom