apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jqPathExpressions:
    - .data
    - .stringData
    - .metadata.labels
    - .metadata.annotations
  - group: ""
    kind: Secret
    name: argocd-notifications-secret
    jqPathExpressions:
    - .data
    - .stringData
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 10.1.1
    helm:
      releaseName: argocd
      valuesObject:
        applicationSet:
          replicas: 0
        configs:
          secret:
            createSecret: false
          cm:
            resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
              jqPathExpressions:
              - .spec.preserveUnknownFields
            resource.customizations.ignoreDifferences.apps_StatefulSet: |
              jqPathExpressions:
              - .spec.volumeClaimTemplates[].metadata.creationTimestamp
            resource.trackingmethod: annotation
          params:
            otlp.address: otel-collector.k8s.somemissing.info:4317
            otlp.insecure: "false"
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prom
              enabled: true
          replicas: 1
        dex:
          enabled: false
        redis:
          exporter:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prom
              enabled: true
        redis-ha:
          enabled: false
        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 1
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prom
              enabled: true
        server:
          autoscaling:
            enabled: true
            minReplicas: 1
          certificate:
            additionalHosts:
            - argocd.k8s.somemissing.info
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prom
              enabled: true
          service:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: argocd.k8s.somemissing.info
