apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  source:
    chart: kubernetes-secret-generator
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
    helm:
      releaseName: kubernetes-secret-generator
      valuesObject: {}