apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-vmubtkube-a
  namespace: argocd
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-vmubtkube-a-deploy-key
        metadataPolicy: None
      secretKey: sshPrivateKey
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argocd-repo-vmubtkube-a
    template:
      data:
        enableLfs: "true"
        insecure: "false"
        name: vmubtkube-a
        sshPrivateKey: |
          {{ .sshPrivateKey }}
        url: ssh://git@github.com/nijave/vmubtkube-a.git
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
