apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8s-ca
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: k8s-ca
  secretName: k8s-ca-tls
  duration: 87660h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: k8s-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: k8s
  namespace: cert-manager
spec:
  ca:
    secretName: k8s-ca-tls
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        caProvider:
            type: ConfigMap
            name: kube-root-ca.crt
            key: ca.crt
      auth:
        serviceAccount:
          name: cert-manager
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-ca
  namespace: cert-manager
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: cert-manager
  target:
    name: k8s-ca
  data:
  - secretKey: ca.crt
    remoteRef:
      key: k8s-ca-tls
      property: tls.crt
      conversationStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: k8s-ca
  namespace: cert-manager
spec:
  delegations:
    - secretName: k8s-ca
      targetNamespaces:
      - "*"
---