---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list"]
  - apiGroups: ["projectcontour.io"]
    resources: ["httpproxies"]
    verbs: ["watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rfc2136-tsig-secret
  namespace: external-dns
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  data:
  - secretKey: tsig-secret
    remoteRef:
      conversionStrategy: Default
      key: external-dns-opnsense
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        # image: registry.k8s.io/external-dns/external-dns:v0.17.0
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        imagePullPolicy: IfNotPresent
        env:
          - name: TSIG_SECRET
            valueFrom:
              secretKeyRef:
                name: rfc2136-tsig-secret
                key: tsig-secret
        args:
        - --registry=txt
        - --txt-prefix=external-dns-
        - --txt-owner-id=k8s
        - --provider=rfc2136
        - --rfc2136-host=172.16.3.253
        - --rfc2136-port=53
        - --rfc2136-zone=apps.somemissing.info
        - --domain-filter=apps.somemissing.info
        - --rfc2136-zone=k8s.somemissing.info
        - --domain-filter=k8s.somemissing.info
        - --rfc2136-tsig-secret-alg=hmac-sha256
        - --rfc2136-tsig-keyname=external-dns
        - --rfc2136-tsig-secret=$(TSIG_SECRET)
        - --rfc2136-tsig-axfr
        - --source=service
        - --source=ingress
        - --source=contour-httpproxy
        - --publish-internal-services
        - --log-level
        - debug
