apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-syslog-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          syslog
        Tag           syslog.udp
        Listen        0.0.0.0
        Port          5140
        Mode          udp
        Parser        syslog-rfc5424

    [INPUT]
        Name          syslog
        Tag           syslog.tcp
        Listen        0.0.0.0
        Port          5140
        Mode          tcp
        Parser        syslog-rfc5424

    [OUTPUT]
        Name          stdout
        Match         syslog.*
        Format        json_lines

  parsers.conf: |
    [PARSER]
        Name        syslog-rfc5424
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<version>[0-9])\s+(?<time>[^ ]+)\s+(?<host>[^ ]+)\s+(?<app>[^ ]+)\s+(?<proc>[^ ]+)\s+(?<msgid>[^ ]+)\s+(?<sd>(\[[^\]]*\]|-))\s*(?<message>.*)$
        # Time_Key    time
        # Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        # Time_Keep   On
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit-syslog
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit-syslog
  template:
    metadata:
      labels:
        app: fluent-bit-syslog
    spec:
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:4.2
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          ports:
            - name: syslog-udp
              containerPort: 5140
              protocol: UDP
            - name: syslog-tcp
              containerPort: 5140
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: config
          configMap:
            name: fluent-bit-syslog-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-syslog
  namespace: monitoring
spec:
  selector:
    app: fluent-bit-syslog
  type: ClusterIP
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 5140
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 5140
      protocol: TCP
---