---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: monitoring
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        memory: 512Mi
        cpu: 250m
      requests:
        memory: 128Mi
        cpu: 100m
  query:
    resources:
      limits: 
        memory: 768Mi
        cpu: 1000m
      requests:
        memory: 64Mi
        cpu: 25m
  storage:
    type: elasticsearch
    secretName: jaeger-es-creds
    options:
      es:
        tls:
          enabled: true
          skip-host-verify: true
        server-urls: https://default-es-http.elasticsearch.svc.cluster.local.:9200
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jaeger.k8s.somemissing.info
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger-query
    app.kubernetes.io/part-of: jaeger
  name: jaeger-frontend
  namespace: monitoring
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
  - name: http-query
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-query
    app.kubernetes.io/part-of: jaeger