apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: monitoring
spec:
  channel: stable
  name: jaeger
  source: operatorhubio-catalog
  sourceNamespace: olm