---
apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: thanos
  namespace: minio
spec:
  name: thanos
  tenantRef:
    namespace: minio
    name: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-key
  namespace: minio
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secretKey
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/length: "32"
stringData: {}
---
apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: thanos
  namespace: minio
spec:
  accessKey: thanos-app-key
  secretKeyRef:
    name: thanos-key
    key: secretKey
  tenantRef:
    namespace: minio
    name: minio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: thanos-read-write
  namespace: minio
spec:
  name: thanos-read-write
  statement:
    - effect: "Allow"
      action:
        - "s3:AbortMultipartUpload"
        - "s3:DeleteObject"
        - "s3:ListMultipartUploadParts"
        - "s3:PutObject"
        - "s3:GetObject"
      resource:
        - "arn:aws:s3:::thanos/*"
    - effect: "Allow"
      action:
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
      resource:
        - "arn:aws:s3:::thanos"
  tenantRef:
    namespace: minio
    name: minio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: thanos
  namespace: minio
spec:
  policy: thanos-read-write
  tenantRef:
    namespace: minio
    name: minio
  user:
    builtin: thanos