---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: nas.apps.somemissing.info
    path: /media/av/torrents/.torrents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: prowlarr-media
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 40Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-repo-prowlarr
  namespace: media
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: s3:https://vmubthh01.s.nickv.me:/volsync-prowlarr
        RESTIC_PASSWORD: "{{ .password }}"
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
  data:
  - secretKey: password
    remoteRef:
      key: volsync-restic-password-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: accessKey
    remoteRef:
      key: volsync-restic-repo-id-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: secretKey
    remoteRef:
      key: volsync-restic-repo-secret-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-data
  namespace: media
spec:
  sourcePVC: prowlarr-data
  trigger:
    schedule: "*/30 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-repo-prowlarr
    moverSecurityContext:
      runAsUser: 1002
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 3
      yearly: 0
    copyMethod: Clone
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.k8s.somemissing.info
  labels:
    app.kubernetes.io/component: prowlarr
    app.kubernetes.io/name: arr
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/component: prowlarr
    app.kubernetes.io/name: arr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
  labels:
    app.kubernetes.io/component: prowlarr
    app.kubernetes.io/name: arr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: prowlarr
      app.kubernetes.io/name: arr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prowlarr
        app.kubernetes.io/name: arr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        env:
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "1002"
        - name: PGID
          value: "1001"
        ports:
        - containerPort: 9696
          name: http
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 5
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        resources:
          requests:
            memory: 256Mi
            cpu: 25m
          limits:
            memory: 4Gi
            cpu: 250m
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-data
      - name: downloads
        persistentVolumeClaim:
          claimName: prowlarr-media
---