apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-apps-somemissing-info-cert
  namespace: default
spec:
  secretName: frigate-apps-somemissing-info-tls
  issuerRef:
    name: cert-manager-webhook-dnsimple-production
    kind: ClusterIssuer
  commonName: &cn frigate.apps.somemissing.info
  dnsNames:
    - *cn
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frigate-apps-somemissing-info
  namespace: default
spec:
  virtualhost:
    fqdn: frigate.apps.somemissing.info
    tls:
      secretName: frigate-apps-somemissing-info-tls
      clientValidation:
        caSecret: ca-ha-homelab-somemissing-info-tls
        optionalClientCertificate: true
    authorization:
      extensionRef:
        name: python-envoy-authz
        namespace: projectcontour
  routes:
    - conditions:
        - prefix: /
      requestHeadersPolicy:
        set:
        - name: x-forwarded-user
          value: admin
        - name: x-forwarded-groups
          value: admin
      services:
        - name: hassio-homelab-somemissing-info
          port: 8081
      timeoutPolicy:
        response: 24h
      enableWebsockets: true
---