---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: nas.apps.somemissing.info
    path: /media/av
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: sabnzbd-media
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.k8s.somemissing.info
  labels:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/name: arr
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/name: arr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/name: arr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: sabnzbd
      app.kubernetes.io/name: arr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sabnzbd
        app.kubernetes.io/name: arr
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        # command: [sleep, infinity]
        env:
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "1002"
        - name: PGID
          value: "1001"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        resources:
          requests:
            memory: 256Mi
            cpu: 25m
          limits:
            memory: 4Gi
            cpu: 2000m
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-data
      - name: media
        persistentVolumeClaim:
          claimName: sabnzbd-media
---