
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: libvirt
  labels:
    class: ssd
    redundancy: "1"
    tier: mid
parameters:
  type: libvirt
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: libvirt-high
  labels:
    class: nvme
    redundancy: "1"
    tier: high
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: libvirt
  volumeGroup: volume-high/thigh
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: libvirt-low
  labels:
    class: hdd
    redundancy: "1-0"
    tier: low
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: libvirt
  volumeGroup: volume-low/tlow
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: libvirt-mid-nr
  labels:
    class: ssd
    redundancy: none
    tier: mid
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: libvirt
  volumeGroup: volume01/tmid-nr
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
  name: libvirt-mid
  labels:
    class: ssd
    redundancy: "1"
    tier: mid
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: libvirt
  volumeGroup: zvol:midline/k8s
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: libvirt-xfs
  labels:
    class: ssd
    redundancy: "1"
    tier: mid
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: libvirt
  volumeGroup: file:/volume-med/pvs
provisioner: libvirt-csi.nijave.github.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
