apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit-syslog
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit-syslog
  template:
    metadata:
      labels:
        app: fluent-bit-syslog
    spec:
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:5.0
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          ports:
            - name: syslog-udp
              containerPort: 5140
              protocol: UDP
            - name: syslog-tcp
              containerPort: 5140
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: config
          configMap:
            name: fluent-bit-syslog-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-syslog
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/hostname: syslog.k8s.somemissing.info
spec:
  selector:
    app: fluent-bit-syslog
  type: ClusterIP
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 5140
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 5140
      protocol: TCP
