apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  source:
    repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.11.1
    helm:
      releaseName: immich
      valuesObject:
        common:
          controllers:
            main:
              containers:
                main:
                  envFrom:
                    - secretRef:
                        name: immich-postgres
        controllers:
          main:
            containers:
              main:
                image:
                  repository: ghcr.io/immich-app/immich-server
                  tag: v2.7.5
                resources:
                  requests:
                    cpu: 50m
        immich:
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: immich
        valkey:
          enabled: true
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: docker.io/valkey/valkey
                    tag: 9.1-alpine@sha256:34f4f659e02a67cfdf3995d11ae432219c936005055b2cd39a042e86280e053e
                    pullPolicy: IfNotPresent
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich
  namespace: immich
  labels:
    release: prom
spec:
  jobLabel: immich-server
  namespaceSelector:
    matchNames:
      - immich
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server
      app.kubernetes.io/service: immich-server
  endpoints:
    - port: metrics-api
      scheme: http
    - port: metrics-ms
      scheme: http
