apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-repo
  namespace: immich
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: s3:https://vmubthh01.s.nickv.me:/volsync-immich
        RESTIC_PASSWORD: "{{ .password }}"
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
  data:
  - secretKey: password
    remoteRef:
      key: volsync-restic-password-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: accessKey
    remoteRef:
      key: volsync-restic-repo-id-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: secretKey
    remoteRef:
      key: volsync-restic-repo-secret-1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich
  namespace: immich
spec:
  sourcePVC: immich
  trigger:
    schedule: "*/30 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-repo
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 3
      yearly: 0
    copyMethod: Clone
---