apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
  name: postgres-immich-user
  namespace: immich
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: immich
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: immich
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader
  namespace: immich
subjects:
  - kind: ServiceAccount
    name: secret-reader
    namespace: immich
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s
  namespace: immich
spec:
  provider:
    kubernetes:
      remoteNamespace: immich
      server:
        caProvider:
            type: ConfigMap
            name: kube-root-ca.crt
            key: ca.crt
      auth:
        serviceAccount:
          name: secret-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s
  target:
    name: immich-postgres
    template:
      engineVersion: v2
      type: Opaque
      data:
        DB_HOSTNAME: immich-rw.immich.svc.cluster.local
        DB_DATABASE_NAME: immich
        DB_USERNAME: immich
        DB_PASSWORD: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: postgres-immich-user
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
  name: postgres-superuser
  namespace: immich
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: postgres
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: backup-creds
  namespace: immich
spec:
  forceRegenerate: false
  # data:
  #   username: "testuser"
  fields:
    - fieldName: ACCESS_KEY_ID
      encoding: hex
      length: "16"
    - fieldName: ACCESS_SECRET_KEY
      encoding: base32
      length: "32"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: immich
spec:
  # imageName: ghcr.io/cloudnative-pg/postgresql:18.0-system-trixie
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  postgresql:
    parameters:
      shared_buffers: 256MB
      random_page_cost: '1.1'
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '5s'
    shared_preload_libraries:
    - "vchord.so"

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  storage:
    size: 25Gi

  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://postgres/
  #     endpointURL: http://nas.apps.somemissing.info.:9001
  #     s3Credentials:
  #       accessKeyId:
  #         name: backup-creds
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: backup-creds
  #         key: ACCESS_SECRET_KEY
  #     wal:
  #       compression: gzip
  #       encryption: AES256
  #     data:
  #       compression: gzip
  #       encryption: AES256
  #       immediateCheckpoint: false
  #       jobs: 2
  #   retentionPolicy: "30d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    # topologyKey: failure-domain.beta.kubernetes.io/zone
    topologyKey: kubernetes.io/hostname

  enablePDB: true
  
  managed:
    roles:
    - name: immich
      ensure: present
      inherit: true
      connectionLimit: -1
      login: true
      superuser: false
      passwordSecret:
        name: postgres-immich-user
---
# apiVersion: postgresql.cnpg.io/v1
# kind: Pooler
# metadata:
#   name: postgres-pool
#   namespace: immich
# spec:
#   cluster:
#     name: immich
#   instances: 2
#   type: rw
#   pgbouncer:
#     poolMode: session
#     parameters:
#       max_client_conn: "250"
#       default_pool_size: "5"
# ---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  namespace: immich
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-immich
  namespace: immich
spec:
  cluster:
    name: immich
  name: immich
  owner: immich
  extensions:
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
---