apiVersion: v1
kind: Service
metadata:
  name: immich-local
  namespace: projectcontour
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich.apps.somemissing.info
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: envoy