{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "garage.serviceAccountName" . }}
rules:
- verbs: ["create", "get"]
  apiGroups: [""]
  resources: ["secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "garage.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "garage.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "garage.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "garage.serviceAccountName" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
