[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          syslog
    Tag           syslog.udp
    Listen        0.0.0.0
    Port          5140
    Mode          udp
    Parser        syslog-rfc5424

[INPUT]
    Name          syslog
    Tag           syslog.tcp
    Listen        0.0.0.0
    Port          5140
    Mode          tcp
    Parser        syslog-rfc5424

[OUTPUT]
    Name          opentelemetry
    Match         syslog.*
    Host          hyperdx-otel-collector.hyperdx.svc.cluster.local
    Port          4318
    Logs_uri      /v1/logs
    Tls           Off
    Header        authorization 67591567-eca7-43b1-b218-4af3992e5e9b
    Compress      gzip
    Log_response_payload False
