[PARSER]
    Name        syslog-rfc5424
    Format      regex
    Regex       ^\<(?<pri>[0-9]+)\>(?<version>[0-9])\s+(?<time>[^ ]+)\s+(?<host>[^ ]+)\s+(?<app>[^ ]+)\s+(?<proc>[^ ]+)\s+(?<msgid>[^ ]+)\s+(?<sd>(\[[^\]]*\]|-))\s*(?<message>.*)$
    # Time_Key    time
    # Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    # Time_Keep   On
