apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/Altinity/clickhouse-operator
    path: deploy/helm/clickhouse-operator/crds
    targetRevision: 0.26.2
    directory:
      recurse: false
