apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.14.0
    helm:
      releaseName: eck-operator
      valuesObject: {}