---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: minio
  namespace: minio
spec:
  targetNamespaces:
  - minio-tenant
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: minio
  namespace: minio
spec:
  channel: stable
  name: minio-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    env:
      - name: PROMETHEUS_NAMESPACE
        value: monitoring