apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
  name: thanos-query-endpoints
  namespace: thanos
data:
  endpoints.yaml: |
    endpoints:
    - address: dnssrv+_grpc._tcp.thanos-receive-ingestor-default.thanos.svc.cluster.local:10901
    - address: dnssrv+_grpc._tcp.thanos-store.thanos.svc.cluster.local:10901
