apiVersion: v1
kind: Secret
metadata:
  name: thanos-store-caching-bucket
  namespace: thanos
type: Opaque
stringData:
  cache.yaml: |
    type: MEMCACHED
    config:
      addresses:
      - "dns+caching-bucket-memcached.thanos.svc.cluster.local:11211"
      dns_provider_update_interval: "10s"
      max_item_size: "1MiB"
      timeout: "50ms"