apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objectstorage
  namespace: thanos
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: thanos-objectstorage
    template:
      type: Opaque
      data:
        thanos.yaml: |
          type: S3
          config:
            endpoint: nas.apps.somemissing.info.:9001
            insecure: true
            bucket: thanos
            access_key: "{{ .accessKey }}"
            secret_key: "{{ .secretKey }}"
            http_config:
              tls_config:
                ca_file: /etc/kubernetes/pki/ca.crt
  data:
    - secretKey: accessKey
      remoteRef:
        key: thanos-objectstorage-access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secretKey
      remoteRef:
        key: thanos-objectstorage-secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
